Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/Next:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Exclude:
    - "gettext_i18n_rails_js.gemspec"
    - "**/*_spec.rb"
  ExcludedMethods:
    - "namespace"
